name: Curl Test

on: 
    push:
      branches:
        - main
        
jobs:
    Delete-File:
        runs-on: ubuntu-latest
        permissions:
            contents: write
            pull-requests: write
        steps:
            - name: Git checkout
              uses: actions/checkout@v2
              with:
                fetch-depth: 0
            - name: Remove file and create PR
              run: |
                git config user.name "GitHub Actions Bot"
                git config user.email "<>"
                git checkout PORTFOLIO-actions
                git merge main
                git rm -r --ignore-unmatch .github dev .gitattributes .gitignore server.js package-lock.json package.json README.md
                git add -A
                git commit -m "Removed Unecessary Files"
                git push origin PORTFOLIO-actions
                gh pr create --base PORTFOLIO --head PORTFOLIO-actions --title "Deleted files" --body "Deleted files via on push Workflow"
              env:
                GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}